export const types = {
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	UPDATE_CART: 'UPDATE_CART',

	USER_LOGIN: 'USER_LOGIN',
	USER_LOGOUT: 'USER_LOGOUT',
	USER_REGISTER: 'USER_REGISTER',
};
